# Modelo de deep learning com keras
    A biblioteca keras utiliza como padrão a biblioteca tensorflow, porém, abstrai esta última, 
    tornando o trabalho muito menos complexo.
    A keras pode ser utilizada com diversos outros frameworks de deep learning.

In [1]:
from sklearn import datasets
from sklearn .model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

In [2]:
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

    Transformação da variável classe em dummy, ou seja, a realização da transformação da variável categórica classe, 
    em uma matriz na qual será indicado somente se a classe pertence ou não a cada categoria, sendo 1 = verdadeiro 
    e 0 = falso.

In [3]:
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

    Divisão da variável classe_dummy em variáveis de treino e teste com 70% para o primeiro e 30% para o segundo.

In [4]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, classe_dummy, test_size= 0.3, random_state=0)

    Criação da estrutura do modelo da rede neural, com a sequencia de camadas.

In [5]:
# Criação do objeto modelo, o qual é do tipo Sequential, o que será utilizado para para incluir as camadas uma após a outra.
modelo = Sequential()

#Primeira camada com 5 neurônios sendo 4 de entrada (um para cada característica das classes).
modelo.add(Dense(units=5, input_dim= 4))

# Segunda camada
modelo.add(Dense(units= 4))

#terceira camada com 3 neurônios, já que existem somente 3 classes e a função softmax, para lidar com mais de duas classes.
modelo.add(Dense(units= 3, activation= 'softmax'))

    Sumário com o resumo de como a rede foi construída

In [6]:
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


    Utilização do método compile, utilizando os parâmetros mais comuns para otimizar os pesos da rede, sendo que
    o optimizer implementa o algorítmo adam, a loss function calcula o erro entre os valores previstos e os valores 
    reais e a métrica que irá medir o erro, também conhecida como taxa de acerto.

    Também a realização do treinamento do modelo, declarando quais variáveis deverão ser utilizadas para o treinamento 
    e quais para o teste, sendo que os dois são realizados em conjunto.

In [7]:
modelo.compile(optimizer= 'adam', loss= 'categorical_crossentropy', metrics= ['accuracy'])
modelo.fit(x_treino, y_treino, epochs= 1000, validation_data= (x_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 1s 71ms/step - loss: 3.1317 - accuracy: 0.3238 - val_loss: 2.6261 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 10ms/step - loss: 2.8537 - accuracy: 0.3238 - val_loss: 2.3716 - val_accuracy: 0.3556
Epoch 3/1000
4/4 [==============================] - 0s 10ms/step - loss: 2.5852 - accuracy: 0.3238 - val_loss: 2.1314 - val_accuracy: 0.3556
Epoch 4/1000
4/4 [==============================] - 0s 11ms/step - loss: 2.3371 - accuracy: 0.3238 - val_loss: 1.9091 - val_accuracy: 0.3556
Epoch 5/1000
4/4 [==============================] - 0s 11ms/step - loss: 2.1017 - accuracy: 0.3238 - val_loss: 1.7068 - val_accuracy: 0.3556
Epoch 6/1000
4/4 [==============================] - 0s 9ms/step - loss: 1.8872 - accuracy: 0.3238 - val_loss: 1.5242 - val_accuracy: 0.3556
Epoch 7/1000
4/4 [==============================] - 0s 10ms/step - loss: 1.7051 - accuracy: 0.3238 - val_loss: 1.3624 - val_accuracy: 0.3556
Epoch 8/1000
4

    Realização de uma previsão com o x_teste, levando em conta que a previsão retorna uma matriz de 0 e 1 foi realizada 
    a transformação em valores booleanos na segunda linha.

In [8]:
previsoes= modelo.predict(x_teste)
previsoes= (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

    Para criar a matriz de confusão serão criadas duas variáveis, através de 
    loops, tendo em vista que o algoritmo possui três saídas será utilizada a função argmax do numpy, para pegar
    apenas o maior valor, qual seja, o valor True.

In [14]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

    A matriz de confusão reflete exatamente o que a acurácia de 98% apresentada no modelo aponta.
    O teste apresentou apenas um erro, o que é muito superior aos resultados possíveis de serem obtidos
    com outros algorítimos que não envolvam deep learning.

In [22]:
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])